### ISSUE TITLE
runit support

### ISSUE THREAD

**Issue by mthssdrbrg** [mthssdrbrg/kafka-cookbook#10]
A lot of people seem to use `runit`, so why not include support for that as well.

**Comment by spuder** [comment]
+1

Just a heads up, it seems every cookbook I use that depends on the runit cookbook has race condition issues. 
You have to do ugly workarounds like this:

```ruby
runit_service "myservice" do
  # ...
  sv_bin 'sleep 5 && /usr/bin/sv'
  action  :enable
end
```
https://github.com/hw-cookbooks/runit/issues/142
https://github.com/lusis/chef-kibana/issues/106

**Comment by mthssdrbrg** [comment]
Thanks for the heads up! Sure looks ugly, but it seems like it has been [resolved though?](https://github.com/hw-cookbooks/runit/issues/142#issuecomment-147880783)

**Comment by spuder** [comment]
I don't have confidence in the fix, because even though I'm using the latest runit, I still see occasional failures when provisioning and modifying logstash, kibana and kafka nodes.  I haven't looked too deep into it because running chef twice works around the issue. 

    knife cookbook show runit
    runit   1.7.4  1.7.2  1.6.0  1.5.18  1.5.16  1.5.10

**Comment by mthssdrbrg** [comment]
Aight, good to know, I'll most likely include the workaround :)
