### ISSUE TITLE
Restart coordination - is called everytime

### ISSUE THREAD

**Issue by csghuser** [mthssdrbrg/kafka-cookbook#101]
Hello, 

I'm using the restart coordination as described in the readme, e.g.

```
ruby_block 'coordinate-kafka-start' do
  block do
    Chef::Log.info 'Custom recipe to coordinate Kafka start/restart'
  end
  action :create
  notifies :create, 'ruby_block[restart-coordination]', :delayed
end

ruby_block 'restart-coordination' do
  block do
    Chef::Log.info 'Implement the process to coordinate the restart, like using ZK'
  end
  action :nothing
  notifies :restart, 'service[kafka]', :delayed
  notifies :create, 'ruby_block[restart-coordination-cleanup]', :delayed
end

service 'kafka' do
  provider kafka_init_opts[:provider]
  supports start: true, stop: true, restart: true, status: true
  action kafka_service_actions
end

ruby_block 'restart-coordination-cleanup' do
  block do
    Chef::Log.info 'Implement any cleanup logic required after restart like releasing locks'
  end
  action :nothing
end
```

The problem I'm seeing is that no matter if any changes have been made to the kafka config, kafka is being restarted. Should this be happening? Has anyone else seen this?

It would be preferable if kafka was only notified to restart when an aspect of the configuration which required a restart was changed.

**Comment by csghuser** [comment]
I guess this is because of the following

In the _configure.rb recipe we have:

```
include_recipe node.kafka.start_coordination.recipe
```

So no matter what the coordination recipe is being called. 

Because the action on the first ruby block is create, this will always run:

```
ruby_block 'coordinate-kafka-start' do
  block do
    Chef::Log.info 'Custom recipe to coordinate Kafka start/restart'
  end
  action :create
  notifies :create, 'ruby_block[restart-coordination]', :delayed
end
```

Is there a way around this? I think I set the action to be nothing but then it was never restarted.

**Comment by mthssdrbrg** [comment]
Hm, this sound wrong. Just to clarify, are you also setting the `kafka.automatic_restart` attribute to `true`?

The action on the `ruby_block[coordinate-kafka-start]` should be `:nothing`, otherwise it'll restart Kafka on every Chef run (as you pointed out), so that's a mistake in the README.

With `kafka.automatic_restart = true` and `:nothing` action on the `coordinate-kafka-start` block it should work as expect. I'll try to reproduce this locally.

**Comment by mthssdrbrg** [comment]
Did some testing of this locally and it works as expected if the action of `ruby_block[coordinate-kafka-start]` is set to `:nothing` and `kafka.automatic_restart` is set to `true`. Would be great if you could test that out and see if it works on your end as well.

I realized that the [Controlling restart of Kafka brokers in a cluster](https://github.com/mthssdrbrg/kafka-cookbook#controlling-restart-of-kafka-brokers-in-a-cluster) section doesn't mention the `automatic_restart` attribute at all, which it definitely should.

**Comment by csghuser** [comment]
@mthssdrbrg 

Works absolutely perfectly :+1: 

So as you said, you need to set the action to be nothing in this block:

```
ruby_block 'coordinate-kafka-start' do
  block do
    Chef::Log.info 'Custom recipe to coordinate Kafka start/restart'
  end
  action :nothing
  notifies :create, 'ruby_block[restart-coordination]', :delayed
end
```

With the following attribute:

```
default['kafka']['automatic_restart'] = true
```

Then everything works exactly as you would expect, kafka is only restarted when a configuration change is made. 

Thanks for taking a look at this, very much appreciated!!!!
