### ISSUE TITLE
Cookbook uses pre 12.5.1 resource style

### ISSUE THREAD

**Issue by cullenmcdermott** [mthssdrbrg/kafka-cookbook#105]
Is there a necessity with the cookbook to maintain compatibility with Chef 11.6.0? Switching to the new style of creating custom resources would change the minimum version to 12.5.1 but that's a fairly easy upgrade from 11.6.0.

**Comment by mthssdrbrg** [comment]
For now, yes (I'm still mainly running Chef 11 and while an upgrade is overdue it won't happen in the near future).

Is there any problem with using the legacy style of creating custom resources with newer versions of Chef?

**Comment by cullenmcdermott** [comment]
No, I don't think there is an issue with using the legacy style custom resources currently. However I'm wondering if the compat_resource cookbook could be used to make this work with the new resource style. Though I'm not sure if any version of the cookbook supports anything < Chef 12.

**Comment by cullenmcdermott** [comment]
And in my experience moving from Chef 11 to Chef 12 was a passive change, I don't recall having to make any updates to my cookbooks or roles to make the switch, just in case that's what you are worried about with upgrading. 😄

**Comment by mthssdrbrg** [comment]
I was setting up Chef Server at work and ran into issues when attempting to upload some of our cookbooks with `knife` from Chef 12, so unfortunately it's not a passive change for us :).

Currently I don't see any immediate benefit in dropping support for Chef 11, but it might be something to consider for the next major version.
