### ISSUE TITLE
Notify kafka service to reload on service template change

### ISSUE THREAD

**Issue by csghuser** [mthssdrbrg/kafka-cookbook#110]
In the section below, if a value is change, for example the ulimit_file parameter, kafka is restarted however the change is not picked up in the case of a systemd service as the service is not reloaded. 

```
template kafka_init_opts[:script_path] do
  source kafka_init_opts[:source]
  owner 'root'
  group 'root'
  mode kafka_init_opts[:permissions]
  variables({
    daemon_name: 'kafka',
    port: node['kafka']['broker']['port'],
    user: node['kafka']['user'],
    env_path: kafka_init_opts[:env_path],
    ulimit: node['kafka']['ulimit_file'],
    kill_timeout: node['kafka']['kill_timeout'],
  })
  helper :controlled_shutdown_enabled? do
    !!fetch_broker_attribute(:controlled, :shutdown, :enable)
  end
  if restart_on_configuration_change?
    notifies :create, 'ruby_block[coordinate-kafka-start]', :immediately
  end
end
```

Would it be possible to handle this in this section of the code? I am currently attempting to handle it in the coordinate section.

**Comment by mthssdrbrg** [comment]
@csghuser: ah, nice catch. I've pushed a fix in #111.

**Comment by mthssdrbrg** [comment]
@csghuser: it's currently in master but I should be able to get a release in the next day or so. I'll close this when a new release is out.

**Comment by mthssdrbrg** [comment]
`2.1.0` was just released (due on Supermarket shortly).
