### ISSUE TITLE
Systemd - Add wait for network

### ISSUE THREAD

**Issue by csghuser** [mthssdrbrg/kafka-cookbook#114]
Hello, 

Would it be possible to add the following to the systemd template?

```
[Unit]
Description=kafka daemon
Wants=network-online.target
After=network-online.target
```

To ensure that the network is up and running before kafka attempts to start?

Without this, in the event of a server restart, it's possible that kafka is started before the network is ready (waiting for dhcp address for example). Kafka doesn't seem to handle this very well and crashes with an unable to resolve error (as it tries to connect to the zookeeper cluster). 

Thanks!

**Comment by mthssdrbrg** [comment]
Yep, seems completely reasonable.

**Comment by csghuser** [comment]
Great, thanks again!

**Comment by mthssdrbrg** [comment]
Thanks for reporting it. I'll get it merged later today and cut a new release.
