### ISSUE TITLE
Consider setting 'mode 600' and 'sensitive true' on server.properties

### ISSUE THREAD

**Issue by hrak** [mthssdrbrg/kafka-cookbook#118]
Since Kafka 0.9+ supports SSL, the server.properties potentially contains passphrase info for the server keystore and truststore. This cookbook currently sets file mode 644 on server.properties making it world-readable, which is a security risk.

Setting 'mode 600' and 'sensitive true' solves this and makes sure that the chef-client doesn't output passphrase info to stdout or chef-client logfiles.

**Comment by mthssdrbrg** [comment]
Seems reasonable, addressed in #119.

**Comment by mthssdrbrg** [comment]
Closed by 8a2fe7cfb68a5d34b8d050a09fe667e4579e9f12, hopefully should be a new release with this and `runit` support in next week (currently busy moving).
