### ISSUE TITLE
Kafka restarts immediately twice (v2.2.2)

### ISSUE THREAD

**Issue by rohilsurana** [mthssdrbrg/kafka-cookbook#150]
This issue can be resolved by making restart `:delayed` in `recipes/_service.rb`. It has already been fixed in the master, but is missing in the `v2.x` branch (and the latest release `v2.2.2` as well). Can we cut a new release(v2.2.3) from it with this fixed? 
Happy to submit a PR.

**Comment by mthssdrbrg** [comment]
When is this, on the very initial Chef run or on every Chef run? Are you using any custom `start_coordination` recipe?
The default `start_coordination` recipe will simply do a `notifies :restart, 'service[kafka]', :delayed` ([ref](https://github.com/mthssdrbrg/kafka-cookbook/blob/v2.2.2/recipes/_coordinate.rb#L11)), which _should_ only run at the end of the Chef run (and duplicated notifications will be dealt with by Chef AFAIK).

**Comment by rohilsurana** [comment]
@mthssdrbrg that makes sense, I was under the impression that the lines - [13](https://github.com/mthssdrbrg/kafka-cookbook/blob/cd2eab3ef5abda2719bc8ea9681889e52e47bfb7/recipes/_service.rb#L13) and [37](https://github.com/mthssdrbrg/kafka-cookbook/blob/v2.x/recipes/_service.rb#L37) were causing it.

Also I noticed the same lines in the master branch have `:delayed` timer instead of `: immediately ` and hence wondered if that would be required here as well.

**Comment by mthssdrbrg** [comment]
@rohilsurana just to double check, is this a problem you're currently running into or something that you'd expect to run into due to lines 13 and 17?

**Comment by rohilsurana** [comment]
@mthssdrbrg this happened for me the first time chef-client ran. Will try to reproduce it and reopen the issue. For this issue can be closed.
