### ISSUE TITLE
Start the zookeeper as part of kafka service

### ISSUE THREAD

**Issue by jayeshu** [mthssdrbrg/kafka-cookbook#76]
I am using this recipe in vagrant VM to install and run kafka as a service.
I notice that kafka fails since zookeeper was never started on that VM using service.

~~~
[2015-03-04 19:24:01,515] FATAL Fatal error during KafkaServerStable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
~~~
If I manually run following 

~~~bash
/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties &
~~~
then it works. 

What should be the right approach for bringing the zookeeper automatically as well ?
I only have following in my vagrant file: 
  config.vm.provision "chef_solo" do |chef|
     chef.cookbooks_path = "cookbooks"
	chef.add_recipe "kafka::default"
   end

**Comment by cbaenziger** [comment]
Startup of Zookeeper was removed from the cookbook in pull request #50.

**Comment by mthssdrbrg** [comment]
The ZooKeeper setup was only ever intended to be used for testing purposes during the initial development of this cookbook. I highly recommend that you use a separate cookbook for managing ZooKeeper, as it's a different beast from Kafka. I think the [chef-zookeeper](https://github.com/SimpleFinance/chef-zookeeper) cookbook by SimpleFinance is a good place to start.
