### ISSUE TITLE
Set a default zookeeper.connect value

### ISSUE THREAD

**Issue by ccope** [mthssdrbrg/kafka-cookbook#78]
I'm not very familiar with kafka, but wanted to test out a local cluster. I make a quick wrapper cookbook to get a zookeeper cluster set up, but then it wasn't straightforward to get kafka to connect to it. I had to google around to figure out the right statement to add to the server.properties. What do you think about adding the following attribute?
`default[:kafka][:broker][:'zookeeper.connect'] = 'localhost:2181'`

**Comment by mthssdrbrg** [comment]
The main intent of this cookbook is to set up Kafka cluster(s) in some kind of remote environment, and the README describes how to set attributes for configuring a Kafka broker as well as a link to the official documentation (which describes which configuration options exist). That being said, the section describing how to configure a broker could be better and more thorough, but the basics are there.

I'd like to keep this cookbook free of defaults for broker configuration, and let the Kafka team manage that how they see fit. In retrospect I would've preferred to not set any default broker configuration, but changing the two options that are already set (`broker_id` and `port`) would most certainly break things for anyone that uses this cookbook. Though it's not impossible that there'll be some changes before v1.0.0.

**Comment by ccope** [comment]
Hm, what about a commented-out attribute? Just listing the bare-minimum attributes required to get a working kafka would be nice. Or is the concern that those attributes may change?

**Comment by mthssdrbrg** [comment]
I've added a FAQ section to the README, that contains information on the minimum required setup.
