### ISSUE TITLE
Question - How does this cookbook differ from others

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#86]
There are a couple of kafka cookbooks on the supermarket

For example

https://github.com/MathYourLife/apache_kafka

Does this cookbook exist because of a deficiency in the other kafka cookbooks? Are you planning on maintaining this one for a while?

**Comment by mthssdrbrg** [comment]
If I recall correctly there wasn't any cookbook available that could be used for installing Kafka >= v0.8.0 when I started working on this, and I also wanted to try to create a cookbook that had unit and integration tests (with all bells and whistles). The first commit of the cookbook you linked is from 1st of February 2015, and the first commit of this cookbook is from 6th of July 2013 :).

I plan on maintaining this as long as I think it's fun (and time permits) :).

**Comment by spuder** [comment]
Great thanks!
