### ISSUE TITLE
Any plans for a changelog?

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#87]
I'm running cookbook 0.7.1 and I'm upgrading to cookbook 0.8.0. It isn't easy to tell exactly what changed just by looking at the commit history. 

Any plans to include a changelog file that lists what changed?

**Comment by mthssdrbrg** [comment]
Changes between releases are already (or at least should be) listed for each release here on GitHub, see [kafka-cookbook/releases](https://github.com/mthssdrbrg/kafka-cookbook/releases).

I suppose a changelog wouldn't hurt though, as it can be easier to get an overview. Given that it's possible to fetch each release from GitHub's API it should be pretty straight-forward to generate a changelog :).

**Comment by spuder** [comment]
Thanks for pointing that out. That works.
