### ISSUE TITLE
Plans to release to supermarket?

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#89]
This is a great cookbook. I can't find it on the supermarket though, so I end up having to do the following in my wrapper cookbook berksfile. 

```ruby
source "https://supermarket.getchef.com"

metadata

cookbook 'kafka', github: "mthssdrbrg/kafka-cookbook", tag: "v0.8.0"
cookbook 'cron'
```

Any plans to upload to the supermarket?

**Comment by mthssdrbrg** [comment]
Hm, haven't really thought about it to be honest, but maybe. It would however require a renaming as `kafka` is already taken (and names on the supermarket are global...). I'm generally not fond of cookbook names with a hyphen (thinking to rename it to `kafka-cookbook`), and it causes problems with LWRPs (can be avoided by not using LWRPs).

I'll think about it for the v1.0.0 release that I'm planning for the beginning of next year.
