### ISSUE TITLE
Version bump, conflict with supermarket kafka'

### ISSUE THREAD

**Issue by http-418** [mthssdrbrg/kafka-cookbook#93]
In issue #89, Mathias mentioned that he was planning a 1.0.0 release. Unfortunately, the 'kafka' cookbook on chef supermarket is already at version 1.x.x.

Seeing as the supermarket cookbook has already been deprecated by its author,  would it be reasonable to bump this kafka cookbook to version 2.0.0, so that specifying `depends 'kafka', '~> 2'` in a wrapper cookbook cannot possibly resolve to the supermarket-published 'kafka' ?

**Comment by mthssdrbrg** [comment]
That would be pretty cool, though I don't know much about the Supermarket to be honest, is it possible to "reserve" a name? (I'm guessing not). Or maybe if it would be possible to transfer ownership somehow?

**Comment by http-418** [comment]
It is definitely possible to transfer a name.  I'm not sure how much cooperation you will get from the current owner of 'kafka', since he has replaced it with a new cookbook called 'apache_kafka.'

I would like to see the version bump go to '2.0.0' just to avoid accidental resolution of the wrong cookbook by Berkshelf users.   It would be better to throw an error about failure to find version 2.0.0 than grab the supermarket 'kafka' by accident.

**Comment by mthssdrbrg** [comment]
Cool, I'll reach out to the current owner and to see what's up.

Yeah, think I could live with that, seen the same thing with gems on Rubygems (re: version bump to `>= 2.x.y`).

**Comment by jimdowling** [comment]
Yes, this would be great, as lack of supermarket is a blocker for many installations on firewalled networks that only allow http outgoing access. Supermarket cookbooks work fine with Berkshelf and only outgoing http, but berks-specified github repos are inaccessible, as they use the git protocol to download them.

**Comment by mthssdrbrg** [comment]
Got the ownership transferred [yesterday](https://github.com/Webtrends/kafka/issues/8), and I'll look into releasing `v0.9.0` as `v2.0.0` on Supermarket this weekend.

**Comment by mthssdrbrg** [comment]
Just released `v2.0.0` to [Supermarket](https://supermarket.chef.io/cookbooks/kafka/versions/2.0.0). Let me know if there are any problems (I don't use Supermarket myself :)).

**Comment by BalasekharNelli12** [comment]
Hi, I am using v2.2.0 [ from Supermarket], it was working good since last week. But, all of sudden, getting the below issue. And cookbook is failing to install.

>  Recipe: kafka::_configure
>          * directory[/opt/kafka/config] action create (up to date)
>          * template[/opt/kafka/config/log4j.properties] action create       ==============================================================================
>            Error executing action `create` on resource 'template[/opt/kafka/config/log4j.properties]'          ==============================================================================          
>            Chef::Mixin::Template::TemplateError
>            ------------------------------------
>            undefined method `root_logger' for #<Mash:0x00000004fc62b0>

Thanks

**Comment by mthssdrbrg** [comment]
@BalasekharNelli12: If you could open a separate issue that'd be great, and please include which version of Chef you're using. Thanks.
